import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 *  - create an ordered group of docs
 *  - render a sidebar for each doc of that group
 *  - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Custom sidebar for Module 1
  module1Sidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      collapsed: false,
      items: [
        'module1/README',
        {
          type: 'category',
          label: 'Chapter 1.1: Why ROS 2 is the De Facto Robotic Nervous System',
          items: ['module1/1.1-why-ros2']
        },
        {
          type: 'category',
          label: 'Chapter 1.2: From ROS 1 to ROS 2',
          items: ['module1/1.2-ros1-to-ros2']
        },
        {
          type: 'category',
          label: 'Chapter 1.3: Core Concepts Deep Dive',
          items: [
            'module1/1.3-core-concepts/index',
            'module1/1.3-core-concepts/1.3.1-nodes',
            'module1/1.3-core-concepts/1.3.2-topics',
            'module1/1.3-core-concepts/1.3.3-services-actions',
            'module1/1.3-core-concepts/1.3.4-parameters'
          ]
        }
      ]
    }
  ],

  // Custom sidebar for Module 2
  module2Sidebar: [
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chapter 2.1: Understanding Digital Twins in Robotics',
          items: ['module2/2.1-understanding-digital-twins']
        },
        {
          type: 'category',
          label: 'Chapter 2.2: Gazebo Physics Simulation Fundamentals',
          items: ['module2/2.2-gazebo-physics-fundamentals']
        },
        {
          type: 'category',
          label: 'Chapter 2.3: Creating Environments in Gazebo',
          items: ['module2/2.3-creating-environments']
        },
        {
          type: 'category',
          label: 'Chapter 2.4: Sensor Simulation in Gazebo',
          items: ['module2/2.4-sensor-simulation']
        },
        {
          type: 'category',
          label: 'Chapter 2.5: Unity Integration for High-Fidelity Visualization',
          items: ['module2/2.5-unity-integration']
        },
        {
          type: 'category',
          label: 'Chapter 2.6: Hands-On Lab - Building a Complete Digital Twin',
          items: ['module2/2.6-hands-on-lab']
        },
        {
          type: 'category',
          label: 'Chapter 2.7: Key Takeaways and Future Directions',
          items: ['module2/2.7-key-takeaways']
        }
      ]
    }
  ],

  // Custom sidebar for Module 3
  module3Sidebar: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      collapsed: false,
      items: [
        'module3-isaac/index',
        {
          type: 'category',
          label: 'Chapter 1: Understanding NVIDIA Isaac',
          items: [
            'module3-isaac/chapter1-understanding-nvidia-isaac/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Isaac Sim',
          items: [
            'module3-isaac/chapter2-isaac-sim/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Isaac ROS',
          items: [
            'module3-isaac/chapter3-isaac-ros/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 4: Navigation with Nav2',
          items: [
            'module3-isaac/chapter4-nav2/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 5: Integration',
          items: [
            'module3-isaac/chapter5-integration/index'
          ]
        }
      ]
    }
  ],

  // Custom sidebar for Module 4
  module4Sidebar: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) for Humanoid Robotics',
      collapsed: false,
      items: [
        'module4-vla/index',
        {
          type: 'category',
          label: 'Chapter 1: Understanding the Vision-Language-Action Paradigm',
          items: [
            'module4-vla/chapter1-understanding-vla-paradigm/index',
            'module4-vla/chapter1-understanding-vla-paradigm/vla-architecture',
            'module4-vla/chapter1-understanding-vla-paradigm/key-components',
            'module4-vla/chapter1-understanding-vla-paradigm/real-world-applications'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Voice-to-Action Pipeline with Whisper and LLMs',
          items: [
            'module4-vla/chapter2-voice-to-action/index',
            'module4-vla/chapter2-voice-to-action/whisper-asr',
            'module4-vla/chapter2-voice-to-action/llm-intent-processing',
            'module4-vla/chapter2-voice-to-action/mini-project'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Cognitive Planning for Autonomous Humanoids',
          items: [
            'module4-vla/chapter3-cognitive-planning/index',
            'module4-vla/chapter3-cognitive-planning/task-decomposition',
            'module4-vla/chapter3-cognitive-planning/safety-checks',
            'module4-vla/chapter3-cognitive-planning/planning-algorithms'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 4: Vision-Language Grounding for Object Detection',
          items: [
            'module4-vla/chapter4-vision-language-grounding/index',
            'module4-vla/chapter4-vision-language-grounding/clip-owl-vit',
            'module4-vla/chapter4-vision-language-grounding/object-detection',
            'module4-vla/chapter4-vision-language-grounding/mini-project'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 5: Building the Complete VLA Capstone System',
          items: [
            'module4-vla/chapter5-capstone/index',
            'module4-vla/chapter5-capstone/system-integration',
            'module4-vla/chapter5-capstone/final-capstone'
          ]
        }
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;